version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=production
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - .env.prod

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - .env.prod

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 